// Generated by fetchwise. Edit the spec, not this file.

export interface User { id: number; name: string; email: string }

export interface CreateUser { name: string; email: string }

export interface Session { token: string; userId: number }

export interface Charge { id: string; amount: number; currency: string }

export interface ShopAPI {
  'GET /users': User[];
  'GET /users/:id': {
    params: { id: number };
    response: User;
  };
  'POST /users': {
    body: CreateUser;
    response: User;
  };
  'GET /session': {
    baseURL: "auth";
    response: Session;
  };
  'GET /charges': {
    baseURL: "payments";
    response: Charge[];
  };
  'POST /charges': {
    baseURL: "payments";
    body: { amount: number };
    response: Charge;
  };
}
