// Generated by fetchwise. Edit the spec, not this file.

export interface User { id: number; name: string; email: string }

export interface CreateUser { name: string; email: string }

export interface JsonPlaceholder {
  'GET /users': User[];
  'GET /users/:id': {
    params: { id: number };
    response: User;
  };
  'POST /users': {
    body: CreateUser;
    response: User;
  };
}
