import type { HttpMethod } from "./types.js";

export interface GenerateRoute {
  method: HttpMethod;
  path: string;
  baseURL?: string;
  body?: string;
  query?: string;
  params?: string;
  response: string;
}

export interface GenerateSpec {
  name?: string;
  models?: Record<string, string>;
  routes: GenerateRoute[];
}

function formatModel(name: string, type: string): string {
  const trimmed = type.trim();
  if (trimmed.startsWith("{") || trimmed.startsWith("interface")) {
    return `export interface ${name} ${trimmed.replace(/^interface\s+\w+\s*/, "")}`;
  }
  return `export type ${name} = ${trimmed}`;
}

function formatRoute(route: GenerateRoute): string {
  const key = `'${route.method} ${route.path}'`;
  const fields = [
    route.baseURL ? `baseURL: ${JSON.stringify(route.baseURL)}` : null,
    route.params ? `params: ${route.params}` : null,
    route.query ? `query: ${route.query}` : null,
    route.body ? `body: ${route.body}` : null,
    `response: ${route.response}`,
  ].filter((field): field is string => Boolean(field));

  if (fields.length === 1) {
    return `  ${key}: ${route.response};`;
  }

  return `  ${key}: {\n    ${fields.join(";\n    ")};\n  };`;
}

/**
 * Generate a TypeScript API interface from a small JSON spec.
 * Use this by hand, or via `npx fetchwise generate api.json`.
 */
export function generateTypes(spec: GenerateSpec): string {
  const name = spec.name ?? "API";
  const models = Object.entries(spec.models ?? {})
    .map(([modelName, type]) => formatModel(modelName, type))
    .join("\n\n");

  const routes = spec.routes.map(formatRoute).join("\n");
  const header = "// Generated by fetchwise. Edit the spec, not this file.\n\n";
  const modelBlock = models ? `${models}\n\n` : "";

  return `${header}${modelBlock}export interface ${name} {\n${routes}\n}\n`;
}
